#!/usr/bin/env bash

separate()
{
    local orig_win_name=$(tmux display-message -p '#W')
    local win_name=tmp-$(date +%s)
    tmux rename-window $win_name

    local base_pane_idx=$(tmux display-message -p '#P')
    local next_pane_idx=$base_pane_idx

    for cmd in $@
    do
        if [ $next_pane_idx -ne $base_pane_idx ]; then
            local size=$((100 / ($# + 1 - ($next_pane_idx - $base_pane_idx))))
            tmux split-window -v -t $win_name.$base_pane_idx -p $size
        fi
        tmux send-keys -t $win_name.$next_pane_idx "$cmd" C-m

        next_pane_idx=$(($next_pane_idx + 1))
    done

    tmux rename-window $orig_win_name
}

if ! tmux -V 1>/dev/null 2>&1 ; then
    echo 'tmux not installed' 1>&2
    exit 0
fi

if { [ -z $1 ] && [ -t 0 ] ; } || [ "$1" == '-h' ] || [ "$1" == '--help' ]
then
    cat <<EOF
Usage:
    separate [options] [FILE]

Options:
    -h, --help          show this help message
    --vertical          vertical split
    --horizontal        horizontal split
EOF
    exit 0
fi

IFS=$'\n'
if [ "$1" ] ; then
    cmds=(`cat "$1"`)
else
    cmds=(`cat`)
fi

separate "${cmds[@]}"
